"""add_assistants_table

Revision ID: c12098f677e1
Revises: d89ef8e53a7b
Create Date: 2025-08-11 14:57:01.507330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12098f677e1'
down_revision = 'd89ef8e53a7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subtenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('enabled_functions', sa.JSON(), nullable=True),
    sa.Column('enabled_mcp_tools', sa.JSON(), nullable=True),
    sa.Column('function_parameters', sa.JSON(), nullable=True),
    sa.Column('mcp_tool_parameters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subtenant_id'], ['subtenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chats', sa.Column('assistant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chats', 'assistants', ['assistant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'assistant_id')
    op.drop_table('assistants')
    # ### end Alembic commands ###