"""add_tool_config_to_chat_and_message

Revision ID: d89ef8e53a7b
Revises: fcb1d9f346b2
Create Date: 2025-08-04 21:37:43.119116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89ef8e53a7b'
down_revision = 'fcb1d9f346b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('enabled_functions', sa.JSON(), nullable=True))
    op.add_column('chats', sa.Column('enabled_mcp_tools', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('enabled_functions', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('enabled_mcp_tools', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'enabled_mcp_tools')
    op.drop_column('messages', 'enabled_functions')
    op.drop_column('chats', 'enabled_mcp_tools')
    op.drop_column('chats', 'enabled_functions')
    # ### end Alembic commands ###